export default  [
    {
        name:"Malika",
        price:"100",
        rating:"5",
        person:"person"
    },
    {
        name:"Wom",
        price:"50",
        rating:"2",
        person:"2"
    },
    {
        name:"Jonas",
        price:"200",
        rating:"4",
        person:"3"
    },
    {
        name:"Yett",
        price:"55",
        rating:"1",
        person:"4"
    },
    {
        name:"HeeeHaw",
        price:"20",
        rating:"4",
        person:"5"
    },
    {
        name:"Reee",
        price:"150",
        rating:"4",
        person:"7"
    }
    ,
    {
        name:"Reee",
        price:"150",
        rating:"4",
        person:"8"
    }
    ,
    {
        name:"Reee",
        price:"150",
        rating:"4",
        person:"9"
    }
    ,
    {
        name:"Reee",
        price:"150",
        rating:"4",
        person:"10"
    }
    ,
    {
        name:"Reee",
        price:"150",
        rating:"4",
        person:"2"
    }
    ,
    {
        name:"Reee",
        price:"150",
        rating:"4",
        person:"5"
    }
    ,
    {
        name:"Reee",
        price:"150",
        rating:"4",
        person:"3"
    }
    ,
    {
        name:"Reee",
        price:"150",
        rating:"4",
        person:"1"
    }
    ,
    {
        name:"Reee",
        price:"150",
        rating:"4",
        person:"8"
    }
    ,
    {
        name:"Reee",
        price:"150",
        rating:"4",
        person:"7"
    }

    ,
    {
        name:"Reee",
        price:"150",
        rating:"4",
        person:"10"
    }

]